import { Product, Category, PickupPoint, DeliverySlot } from "@/lib/types";

export const MOCK_CATEGORIES: Category[] = [
  { id: "mock-cat-1", name: "Verdura", icon: null, display_order: 1 },
  { id: "mock-cat-2", name: "Frutta", icon: null, display_order: 2 },
  { id: "mock-cat-3", name: "Formaggio", icon: null, display_order: 3 },
  { id: "mock-cat-4", name: "Pane", icon: null, display_order: 4 },
  { id: "mock-cat-5", name: "Olio", icon: null, display_order: 5 },
  { id: "mock-cat-6", name: "Miele", icon: null, display_order: 6 },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "mock-p-1", producer_id: "mock-prod-1", category_id: "mock-cat-1",
    name: "Pomodori San Marzano",
    description: "Pomodori dolci e carnosi, perfetti per sughi e conserve. Coltivati a terra in pieno campo.",
    price_per_kg: 3.50, unit_type: "kg", quantity_available: 50, image_url: "/images/generated/pomodori.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Azienda Bianchi", company_name: "Azienda Agricola Bianchi", lat: 44.805, lng: 10.315 },
    categories: { name: "Verdura" },
  },
  {
    id: "mock-p-2", producer_id: "mock-prod-1", category_id: "mock-cat-1",
    name: "Zucchine Genovesi",
    description: "Zucchine chiare tenere e saporite, raccolte a mano ogni mattina.",
    price_per_kg: 2.80, unit_type: "kg", quantity_available: 30, image_url: "/images/generated/zucchine.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Azienda Bianchi", company_name: "Azienda Agricola Bianchi", lat: 44.805, lng: 10.315 },
    categories: { name: "Verdura" },
  },
  {
    id: "mock-p-3", producer_id: "mock-prod-1", category_id: "mock-cat-1",
    name: "Melanzane Violette",
    description: "Melanzane dalla polpa soda e senza semi, ideali per parmigiana e grigliate.",
    price_per_kg: 3.20, unit_type: "kg", quantity_available: 40, image_url: "/images/generated/melanzane.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Azienda Bianchi", company_name: "Azienda Agricola Bianchi", lat: 44.805, lng: 10.315 },
    categories: { name: "Verdura" },
  },
  {
    id: "mock-p-4", producer_id: "mock-prod-2", category_id: "mock-cat-2",
    name: "Mele Annurche Campane",
    description: "Mele dalla polpa croccante e profumata, raccolte al giusto punto di maturazione.",
    price_per_kg: 4.00, unit_type: "kg", quantity_available: 60, image_url: "/images/generated/mele.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Fattoria Del Sole", company_name: "Fattoria Del Sole", lat: 44.698, lng: 10.631 },
    categories: { name: "Frutta" },
  },
  {
    id: "mock-p-5", producer_id: "mock-prod-2", category_id: "mock-cat-2",
    name: "Pere Abate Fetel",
    description: "Pere dolcissime dalla forma allungata, perfette da gustare fresche o cotte.",
    price_per_kg: 4.50, unit_type: "kg", quantity_available: 35, image_url: "/images/generated/pere.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Fattoria Del Sole", company_name: "Fattoria Del Sole", lat: 44.698, lng: 10.631 },
    categories: { name: "Frutta" },
  },
  {
    id: "mock-p-6", producer_id: "mock-prod-2", category_id: "mock-cat-2",
    name: "Fragole di Stagione",
    description: "Fragole dolcissime coltivate a terra con pacciamatura naturale.",
    price_per_kg: 7.50, unit_type: "kg", quantity_available: 12, image_url: "/images/generated/fragole.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Fattoria Del Sole", company_name: "Fattoria Del Sole", lat: 44.698, lng: 10.631 },
    categories: { name: "Frutta" },
  },
  {
    id: "mock-p-7", producer_id: "mock-prod-3", category_id: "mock-cat-3",
    name: "Parmigiano Reggiano DOP",
    description: "Stagionato 24 mesi. Prodotto con latte crudo dei nostri allevamenti.",
    price_per_kg: 22.00, unit_type: "kg", quantity_available: 20, image_url: "/images/generated/parmigiano.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Caseificio La Tradizione", company_name: "Caseificio La Tradizione", lat: 44.613, lng: 10.266 },
    categories: { name: "Formaggio" },
  },
  {
    id: "mock-p-8", producer_id: "mock-prod-3", category_id: "mock-cat-3",
    name: "Ricotta Fresca di Bufala",
    description: "Ricotta cremosa artigianale, senza conservanti. Da consumare fresca.",
    price_per_kg: 12.00, unit_type: "kg", quantity_available: 10, image_url: "/images/generated/ricotta.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Caseificio La Tradizione", company_name: "Caseificio La Tradizione", lat: 44.613, lng: 10.266 },
    categories: { name: "Formaggio" },
  },
  {
    id: "mock-p-9", producer_id: "mock-prod-4", category_id: "mock-cat-4",
    name: "Pane a Pasta Madre",
    description: "Pane di grani antichi con lievito madre vivo, crosta croccante e mollica alveolata.",
    price_per_kg: 5.50, unit_type: "kg", quantity_available: 25, image_url: "/images/generated/pane.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Forno I Fratelli", company_name: "Forno A Legna I Fratelli", lat: 44.647, lng: 10.925 },
    categories: { name: "Pane" },
  },
  {
    id: "mock-p-10", producer_id: "mock-prod-4", category_id: "mock-cat-4",
    name: "Focaccia Ligure",
    description: "Focaccia alta e morbida con olio extra vergine e rosmarino fresco.",
    price_per_kg: 6.50, unit_type: "kg", quantity_available: 20, image_url: "/images/generated/focaccia.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Forno I Fratelli", company_name: "Forno A Legna I Fratelli", lat: 44.647, lng: 10.925 },
    categories: { name: "Pane" },
  },
  {
    id: "mock-p-11", producer_id: "mock-prod-4", category_id: "mock-cat-4",
    name: "Grissini Stirati Artigianali",
    description: "Grissini croccanti, tirati a mano uno ad uno. Perfetti per aperitivo.",
    price_per_kg: 9.00, unit_type: "kg", quantity_available: 30, image_url: "/images/generated/bread.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Forno I Fratelli", company_name: "Forno A Legna I Fratelli", lat: 44.647, lng: 10.925 },
    categories: { name: "Pane" },
  },
  {
    id: "mock-p-12", producer_id: "mock-prod-5", category_id: "mock-cat-5",
    name: "Olio EVO Monocultivar",
    description: "Extra vergine da olive Leccino, spremuto a freddo entro 6 ore dalla raccolta.",
    price_per_kg: 16.00, unit_type: "L", quantity_available: 40, image_url: "/images/generated/olio-evo.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Frantoio Emiliano", company_name: "Frantoio Toscano Emiliano", lat: 44.815, lng: 9.978 },
    categories: { name: "Olio" },
  },
  {
    id: "mock-p-13", producer_id: "mock-prod-5", category_id: "mock-cat-5",
    name: "Olive Taggiasche Sott'olio",
    description: "Olive piccole e saporite, messe sott'olio con erbe aromatiche del nostro orto.",
    price_per_kg: 13.00, unit_type: "kg", quantity_available: 15, image_url: "/images/generated/oil.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Frantoio Emiliano", company_name: "Frantoio Toscano Emiliano", lat: 44.815, lng: 9.978 },
    categories: { name: "Olio" },
  },
  {
    id: "mock-p-14", producer_id: "mock-prod-6", category_id: "mock-cat-6",
    name: "Miele di Acacia",
    description: "Miele chiaro e delicato, ideale per dolcificare senza coprire i sapori.",
    price_per_kg: 10.00, unit_type: "kg", quantity_available: 25, image_url: "/images/generated/miele.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Apicoltura Verde", company_name: "Apicoltura Verde", lat: 44.514, lng: 9.992 },
    categories: { name: "Miele" },
  },
  {
    id: "mock-p-15", producer_id: "mock-prod-6", category_id: "mock-cat-6",
    name: "Miele di Castagno",
    description: "Miele scuro dal sapore intenso e amarognolo, ricco di proprietà benefiche.",
    price_per_kg: 11.00, unit_type: "kg", quantity_available: 20, image_url: "/images/generated/miele-castagno.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Apicoltura Verde", company_name: "Apicoltura Verde", lat: 44.514, lng: 9.992 },
    categories: { name: "Miele" },
  },
  {
    id: "mock-p-16", producer_id: "mock-prod-1", category_id: "mock-cat-1",
    name: "Insalata Mista di Campo",
    description: "Mix di lattughino, rucola, valeriana e songino. Lavata e pronta al consumo.",
    price_per_kg: 3.00, unit_type: "kg", quantity_available: 45, image_url: "/images/generated/vegetables.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Azienda Bianchi", company_name: "Azienda Agricola Bianchi", lat: 44.805, lng: 10.315 },
    categories: { name: "Verdura" },
  },
  {
    id: "mock-p-17", producer_id: "mock-prod-2", category_id: "mock-cat-2",
    name: "Albicocche Piemontesi",
    description: "Albicocche succose e zuccherine, raccolte a mano. Solo in stagione!",
    price_per_kg: 6.00, unit_type: "kg", quantity_available: 15, image_url: "/images/generated/fruit.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Fattoria Del Sole", company_name: "Fattoria Del Sole", lat: 44.698, lng: 10.631 },
    categories: { name: "Frutta" },
  },
  {
    id: "mock-p-18", producer_id: "mock-prod-3", category_id: "mock-cat-3",
    name: "Burro di Malga",
    description: "Burro tradizionale da centrifuga, profumato e dal colore paglierino.",
    price_per_kg: 15.00, unit_type: "kg", quantity_available: 8, image_url: "/images/generated/dairy.webp", is_active: true,
    created_at: new Date().toISOString(),
    profiles: { full_name: "Caseificio La Tradizione", company_name: "Caseificio La Tradizione", lat: 44.613, lng: 10.266 },
    categories: { name: "Formaggio" },
  },
];

export const MOCK_PICKUP_POINTS: PickupPoint[] = [
  { id: "mock-pp-1", name: "Mercato Rionale Centro", address: "Via Garibaldi 15, Parma", lat: 44.8015, lng: 10.328 },
  { id: "mock-pp-2", name: "Parcheggio Centro Sportivo", address: "Via delle Acacie 8, Montechiarugolo", lat: 44.695, lng: 10.415 },
  { id: "mock-pp-3", name: "Cooperativa Il Noce", address: "Strada della Repubblica 42, Collecchio", lat: 44.752, lng: 10.215 },
];

export const MOCK_DELIVERY_SLOTS: DeliverySlot[] = [
  { id: "mock-slot-1", pickup_point_id: "mock-pp-1", delivery_date: "2026-05-02", time_start: "09:00", time_end: "12:00", max_orders: 20, current_orders: 5, is_active: true },
  { id: "mock-slot-2", pickup_point_id: "mock-pp-1", delivery_date: "2026-05-04", time_start: "09:00", time_end: "12:00", max_orders: 20, current_orders: 3, is_active: true },
  { id: "mock-slot-3", pickup_point_id: "mock-pp-2", delivery_date: "2026-05-02", time_start: "08:00", time_end: "11:00", max_orders: 15, current_orders: 2, is_active: true },
];
